# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [2]:
print(np.__version__)
print(np.show_config())

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


#### 3. Create a null vector of size 10

In [4]:
np.zeros(10, dtype = 'int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 4.  How to find the memory size of any array

In [8]:
a = np.array([[3, 4, 5],[1, 2, 6]])
a.nbytes

48

#### 5.  How to get the documentation of the numpy add function from the command line? 

In [9]:
np.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [10]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [11]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last)

In [15]:
a = np.array([[3, 4, 5],[1, 2, 6]])
print(a[::-1])

[[1 2 6]
 [3 4 5]]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [18]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [22]:
a = np.array((1, 2, 0, 0, 4, 0))
a.nonzero()

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [27]:
np.random.random((3, 3, 3))

array([[[0.33577054, 0.52545324, 0.49807498],
        [0.55123785, 0.58018706, 0.1737546 ],
        [0.60820226, 0.63046296, 0.40012622]],

       [[0.65577041, 0.39617385, 0.76941654],
        [0.53293117, 0.05609209, 0.31203065],
        [0.12431664, 0.14074456, 0.49142207]],

       [[0.50945637, 0.9717567 , 0.99091698],
        [0.16036124, 0.72038189, 0.22408448],
        [0.7060898 , 0.79253257, 0.02267881]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [30]:
a = np.random.random((10, 10))
print(a.max())
print(a.min())

0.989651778685559
0.0017532477569912608


#### 14. Create a random vector of size 30 and find the mean value

In [31]:
np.random.random((30)).mean()

0.4280020802355129

#### 15. Create a 2d array with 1 on the border and 0 inside

In [36]:
a = np.ones((5,4))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [38]:
a = np.ones((5,4))
np.pad(a, pad_width = 1, constant_values = 0)

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [39]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [46]:
a = np.zeros((5,5))
for i in range(5):
    a[i+1:,i] = i+1
print(a)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 2. 0. 0. 0.]
 [1. 2. 3. 0. 0.]
 [1. 2. 3. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [47]:
a = np.zeros((8,8))
for i in range(8):
    for k in range(8):
        a[i][k]=(i+k)%2
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [51]:
a = np.arange(6*7*8).reshape((6, 7, 8))
x, y, z = np.where(a==99)
print(x, y, z)

[1] [5] [3]
