In [1]:
import numpy as np

In [3]:
arr = np.array([[1, 2, 3],[4, 5, 6]])

In [4]:
type (arr)

numpy.ndarray

In [6]:
arr.size

6

In [7]:
arr.shape

(2, 3)

In [8]:
arr.ndim

2

In [9]:
arr.dtype

dtype('int64')

In [12]:
arr1 = np.array([1, 2, 3])

In [13]:
arr1.shape

(3,)

In [14]:
arr2 = np.array([[1, 2, 3],[4, 5, 6]], dtype = "float")

In [15]:
arr2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [16]:
arr3 = np.array((1, 2, 3))

In [17]:
arr.shape

(2, 3)

In [18]:
arr3.shape

(3,)

In [20]:
np.zeros((3,4), dtype="int")

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [21]:
np.ones((3,4), dtype="int")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [22]:
np.full((3,4), 6, dtype="complex")

array([[6.+0.j, 6.+0.j, 6.+0.j, 6.+0.j],
       [6.+0.j, 6.+0.j, 6.+0.j, 6.+0.j],
       [6.+0.j, 6.+0.j, 6.+0.j, 6.+0.j]])

In [23]:
np.random.random((2, 2))

array([[0.66446155, 0.63724749],
       [0.60459028, 0.87792625]])

In [25]:
arr = np.random.random((3, 4))

In [26]:
arr

array([[0.74908075, 0.135193  , 0.86137743, 0.79707002],
       [0.46002433, 0.32032954, 0.48435931, 0.85970684],
       [0.40064995, 0.87940379, 0.2250583 , 0.41297644]])

In [28]:
np.arange(0, 30, 5)

array([ 0,  5, 10, 15, 20, 25])

In [30]:
np.linspace?

In [31]:
np.linspace(0, 30, 5)

array([ 0. ,  7.5, 15. , 22.5, 30. ])

In [32]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [33]:
arr.reshape((4, 3))

array([[0.74908075, 0.135193  , 0.86137743],
       [0.79707002, 0.46002433, 0.32032954],
       [0.48435931, 0.85970684, 0.40064995],
       [0.87940379, 0.2250583 , 0.41297644]])

In [35]:
arr.flatten()

array([0.74908075, 0.135193  , 0.86137743, 0.79707002, 0.46002433,
       0.32032954, 0.48435931, 0.85970684, 0.40064995, 0.87940379,
       0.2250583 , 0.41297644])

In [36]:
arr.reshape(2, 2, 3)

array([[[0.74908075, 0.135193  , 0.86137743],
        [0.79707002, 0.46002433, 0.32032954]],

       [[0.48435931, 0.85970684, 0.40064995],
        [0.87940379, 0.2250583 , 0.41297644]]])

In [37]:
arr

array([[0.74908075, 0.135193  , 0.86137743, 0.79707002],
       [0.46002433, 0.32032954, 0.48435931, 0.85970684],
       [0.40064995, 0.87940379, 0.2250583 , 0.41297644]])

In [39]:
arr[:2, 2:3]

array([[0.86137743],
       [0.48435931]])

In [40]:
arr[:3, :3]

array([[0.74908075, 0.135193  , 0.86137743],
       [0.46002433, 0.32032954, 0.48435931],
       [0.40064995, 0.87940379, 0.2250583 ]])

In [43]:
arr[::2,::2]

array([[0.74908075, 0.86137743],
       [0.40064995, 0.2250583 ]])

In [44]:
cond = arr > 0.5
arr[cond]

array([0.74908075, 0.86137743, 0.79707002, 0.85970684, 0.87940379])

In [46]:
arr+1

array([[1.74908075, 1.135193  , 1.86137743, 1.79707002],
       [1.46002433, 1.32032954, 1.48435931, 1.85970684],
       [1.40064995, 1.87940379, 1.2250583 , 1.41297644]])

In [47]:
arr-2

array([[-1.25091925, -1.864807  , -1.13862257, -1.20292998],
       [-1.53997567, -1.67967046, -1.51564069, -1.14029316],
       [-1.59935005, -1.12059621, -1.7749417 , -1.58702356]])

In [48]:
#transpose
arr.T

array([[0.74908075, 0.46002433, 0.40064995],
       [0.135193  , 0.32032954, 0.87940379],
       [0.86137743, 0.48435931, 0.2250583 ],
       [0.79707002, 0.85970684, 0.41297644]])

In [49]:
#matrix multiplication
arr*arr

array([[0.56112196, 0.01827715, 0.74197108, 0.63532062],
       [0.21162238, 0.10261101, 0.23460395, 0.73909584],
       [0.16052039, 0.77335102, 0.05065124, 0.17054954]])

In [50]:
arr.max()

0.8794037858647998

In [51]:
arr.max(axis = 1)

array([0.86137743, 0.85970684, 0.87940379])

In [52]:
arr.max(axis = 0)

array([0.74908075, 0.87940379, 0.86137743, 0.85970684])

In [53]:
arr.sum()

6.5852297003309435

In [54]:
arr.cumsum(axis = 1)

array([[0.74908075, 0.88427375, 1.74565118, 2.5427212 ],
       [0.46002433, 0.78035387, 1.26471318, 2.12442002],
       [0.40064995, 1.28005374, 1.50511204, 1.91808848]])

In [56]:
arr+arr

array([[1.49816149, 0.270386  , 1.72275486, 1.59414005],
       [0.92004865, 0.64065908, 0.96871863, 1.71941367],
       [0.80129991, 1.75880757, 0.45011659, 0.82595289]])

In [58]:
#dot product
arr.dot(arr.T)

array([[1.95669081, 1.49036441, 0.94203969],
       [1.49036441, 1.28793318, 0.93005549],
       [0.94203969, 0.93005549, 1.15507219]])

In [62]:
np.sin(arr)

array([[0.68096586, 0.13478155, 0.75874053, 0.71531168],
       [0.4439699 , 0.31487935, 0.46564147, 0.75765126],
       [0.39001691, 0.77035886, 0.22316319, 0.40133732]])

In [63]:
np.sqrt(arr)

array([[0.86549451, 0.36768601, 0.92810421, 0.89278778],
       [0.67825093, 0.56597662, 0.69595928, 0.92720377],
       [0.63296916, 0.93776531, 0.4744031 , 0.64263243]])

In [66]:
arr.sort()
arr

array([[0.135193  , 0.74908075, 0.79707002, 0.86137743],
       [0.32032954, 0.46002433, 0.48435931, 0.85970684],
       [0.2250583 , 0.40064995, 0.41297644, 0.87940379]])

In [69]:
arr.sort(axis = 0)
arr

array([[0.135193  , 0.40064995, 0.41297644, 0.85970684],
       [0.2250583 , 0.46002433, 0.48435931, 0.86137743],
       [0.32032954, 0.74908075, 0.79707002, 0.87940379]])

In [70]:
a = np.array([[1, 2],[3,4]])

In [72]:
b = np.array([[1, 2],[3,4]])

In [74]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [75]:
np.hstack((a,b))

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [80]:
c = np.array([[2],[3]])

In [81]:
np.column_stack((a,c))

array([[1, 2, 2],
       [3, 4, 3]])

In [82]:
np.concatenate((a,b),1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [87]:
np.hsplit(arr, 1)

[array([[0.135193  , 0.40064995, 0.41297644, 0.85970684],
        [0.2250583 , 0.46002433, 0.48435931, 0.86137743],
        [0.32032954, 0.74908075, 0.79707002, 0.87940379]])]